repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
      exclude: '^data/'
      args: [ --maxkb=50000 ]
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
      exclude: '^data/'
    - id: mixed-line-ending
      exclude: '^data/'
    - id: trailing-whitespace
      exclude: '^data/'
      args:
        - --markdown-linebreak-ext=md
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.287
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      language_version: python3.11
