learning_rate: 1e-6
max_epochs: 1
use_lora: true
tune_learning_rate: false
val_check_interval: 1000
log_every_n_steps: 100
lora_params:
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
use_gradient_checkpointing: true
load_in_4bit: false
load_in_8bit: true
precision: bf16
num_nodes: 1
weight_decay: 0.05
deepspeed_config: null
