configurations:
  - path: "data/From_API/all_json_Solutions_Demo_Workspace_2024-02-01T08_17_38.json"
    workspace: "Solutions Demo Workspace"
    view_id: "defaultview-545"
  - path: "data/NLP POC (JustAsk)"
    workspace: "Solutions Demo Workspace"
    view_id: ""
  - path: "data/metric_definitions"
    workspace: "Solutions Demo Workspace"
    view_id: ""
  - path: "data/pia-dashboards"
    workspace: "Solutions Demo Workspace"
    view_id: ""
  - path: "data/OPAL"
    workspace: "Solutions Demo Workspace"
    view_id: ""
  - path: "data/ContentPackage_December2023"
    workspace: "Solutions Demo Workspace"
    view_id: ""

ouput_dir: "data/temp"
